<div class="banner">
	<a href="\">
		<img src="\images\logo.jpg" class="logo">
	</a>
	<h2 class="title">Your One Stop Online Shopping Store!</h2>
</div>
<div>
	<img src="\images\grayline.jpg" class="line">
	<img src="\images\redline.jpg" class="line">
</div>
<div id="menu">
<ul>
<li><a href="\">Home</a></li>
<li><a href="\order">Order Form</a></li>
<li><a href="\customer">Happy Customers</a></li>
<li><a href="\about">About Us</a></li>
<li><a href="\contact">Contact Us</a></li>
</ul>
</div>