<!DOCTYPE html>
<html class="<?php print $class; ?>">
<head>
	<title><?php print $title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<?php if(isset($meta) && is_array($meta)): ?>
    <?php foreach($meta as $name => $content): ?>
    <meta name="<?php print $name; ?>" content="<?php print $content; ?>" />
    <?php endforeach; ?>
    <?php endif; ?>
    <link rel="stylesheet" type="text/css" href="\styles\style.css">
	<link rel="stylesheet" type="text/css" href="\styles\bootstrap\css\bootstrap.css">
	<link rel="stylesheet" type="text/css" href="\styles\slick-master\css\style.css"/>
	<script type="text/javascript" src="styles\slick-master\slick-master\js\scripts.js"></script>
	<script type="text/javascript" src="\scripts\jquery.js"></script>
</head>
<body>
	<div class="container">
		<div class="head"><?php echo $head; ?></div>
		<div class="body"><?php echo $body; ?></div>
		<div class="foot"><?php echo $foot; ?></div>
    </div>
</body>
</html>
