<form method="POST" enctype="multipart/form-data">
<input type="file" name="file"/>
Item Name<br/>
<input type="text" name="name"/><br/>
Item Price<br/>
<input type="text" name="price"/><br/>
Item Category<br/>
<select name="category">
	<option value="dress">Dress</option>
	<option value="gadgets">Gadgets</option>
	<option value="jackets">Jackets</option>
	<option value="jumpshorts">Jumpshorts</option>
	<option value="onhand">Onhand Items</option>
	<option value="pullovers">Pullovers</option>
	<option value="shirts">Shirts</option>
	<option value="skirts">Skirts</option>
	<option value="soap">Soap</option>
	<option value="tops">Tops</option>
	<option value="bags">Bags</option>
	<option value="pants">Pants</option>
</select>
<button class="btn-success btn" type="submit">Submit</button>
</form>
